version: 2.1

jobs:
  test:
    docker:
      - image: gcc:latest  # Utilizando a imagem do compilador GCC para C++
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build and Run C++ Test
          command: |
            g++ -o test_calculator test_calculator.cpp
            ./test_calculator

  GENERIC_JOB:
    docker:
      - image: gcc:latest  # Utilizando a imagem do compilador GCC para C++
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run Generic Job
          command: |
            # Algoritmo do job generico, que será executado caso o teste do job "test" não falhe.
            # A verificação de execução ou não é definida no workflow, no bloco "jobs"

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - GENERIC_JOB:
          requires:
            - test
